### ISSUE TITLE
Config Settings

### ISSUE THREAD

**Issue by djarbz** [shvetsgroup/laravel-email-database-log#10]
Hello, I just stumbled upon this as a way to log emails sent. Upon testing it seems to work perfectly. I would, however, like to see a config file where I could change the table name. In my example I name all tables as a category for easier display in PHPmyAdmin. In this case I would name it Logs__Email
This way I can keep all my log tables separated and view uncluttered.

Thank you for your consideration.

**Comment by neochief** [comment]
Just curious, how do you do it for other packages? I've never seen a package that provides such a config.

**Comment by djarbz** [comment]
For example, the squareboat/sneaker package. It creates config\sneaker.php that contains variables that can be set either directly or via environment.

`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Sends an email on Exception or be silent
    |--------------------------------------------------------------------------
    |
    | Should we email error traces?
    |
    */
    'silent' => env('SNEAKER_SILENT', true),

    /*
    |--------------------------------------------------------------------------
    | A list of the exception types that should be captured.
    |--------------------------------------------------------------------------
    |
    | For which exception class emails should be sent?
    |
    | You can also use '*' in the array which will in turn captures every
    | exception.
    |
    */
    'capture' => [
        Symfony\Component\Debug\Exception\FatalErrorException::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Error email recipients
    |--------------------------------------------------------------------------
    |
    | Email stack traces to these addresses.
    |
    */

    'to' => [
        // 'hello@example.com',
    ],

    /*
    |--------------------------------------------------------------------------
    | Ignore Crawler Bots
    |--------------------------------------------------------------------------
    |
    | For which bots should we NOT send error emails?
    |
    */
    'ignored_bots' => [
        'googlebot',        // Googlebot
        'bingbot',          // Microsoft Bingbot
        'slurp',            // Yahoo! Slurp
        'ia_archiver',      // Alexa
    ],
];
`

**Comment by neochief** [comment]
I don't mean any config, I mean a config for a database schema. I've never seen a package that let users change the names of database tables.

**Comment by djarbz** [comment]
`
/*
    |--------------------------------------------------------------------------
    | Laratrust Tables
    |--------------------------------------------------------------------------
    |
    | These are the tables used by Laratrust to store all the authorization data.
    |
    */
    'tables' => [
        /**
         * Roles table.
         */
        'roles' => 'auth__roles',

        /**
         * Permissions table.
         */
        'permissions' => 'auth__permissions',

        /**
         * Teams table.
         */
        'teams' => 'auth__shows',

        /**
         * Role - User intermediate table.
         */
        'role_user' => 'auth__role_user',

        /**
         * Permission - User intermediate table.
         */
        'permission_user' => 'auth__permission_user',

        /**
         * Permission - Role intermediate table.
         */
        'permission_role' => 'auth__permission_role',

    ],
`

**Comment by spaantje** [comment]
Closing old issues. Please let me know if it's still an issue.
