### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by scott80109** [shvetsgroup/laravel-email-database-log#27]
Mail is being sent, but the email_log table remains empty.

**Comment by spaantje** [comment]
Hi @scott80109, can you please provider some more info. Like which version are you using. Which Laravel version are you using? Thanks!

**Comment by scott80109** [comment]
Laravel 8.73.1
Latest version of laravel-email-database-log

**Comment by bertbalcaen** [comment]
Laravel 8.74

- Version 8.0.0 of this package: works
- Version 8.0.1: doesn't work, no emails are logged

**Comment by olipayne** [comment]
Also having the same issue with 8.0.1, will investigate further later but so far I've had to pin 8.0.0 to have my emails log correctly.

**Comment by Enaah** [comment]
Can confirm the same behaviour.

**Comment by spaantje** [comment]
@Enaah @olipayne @bertbalcaen @scott80109 

Can you please confirm that v8.0.2 fixes the issues ?

**Comment by Enaah** [comment]
> @Enaah @olipayne @bertbalcaen @scott80109
> 
> Can you please confirm that v8.0.2 fixes the issues ?

I can confirm, both `8.0.2` and `9.0.0` are working. Test are green again, thanks! ✌🏽

**Comment by scott80109** [comment]
Unfortunately, version 9 is still not working for me with Laravel 8.73.1. I added some debug statements to register() in LaravelEmailDatabaseLogServiceProvider. It seems to be registering the LaravelEmailDatabaseLogEventServiceProvider. I also put some debug statements in the handle() method in EmailLogger. That method is never being executed.

**Comment by spaantje** [comment]
@scott80109 i have just checked a clean install of Laravel 8.73.1 and version 8.0.2 or 9.0.0 of the package are working. 

Can you provide some more info on your situation.
