### ISSUE TITLE
Break package in laravel 5.2

### ISSUE THREAD

**Issue by juniorb2ss** [shvetsgroup/laravel-email-database-log#4]
`[ErrorException]                                                                                                                                                       
  Declaration of ShvetsGroup\LaravelEmailDatabaseLog\LaravelEmailDatabaseLogServiceProvider::boot() should be compatible with Illuminate\Foundation\Support\Providers\E  
  ventServiceProvider::boot(Illuminate\Contracts\Events\Dispatcher $events)`

Pull #3 break package in laravel 5.2.

**Comment by neochief** [comment]
Just use the previous version, please.

**Comment by juniorb2ss** [comment]
Incorrect way to fix. Create tag specific to laravel 5.2 or another service provider to use in laravel 5.2.

But to using previous tag.
