### ISSUE TITLE
Hebrew Subject goes wrong

### ISSUE THREAD

**Issue by Naxon** [shvetsgroup/laravel-email-database-log#7]
When sending an email with an hebrew subject (charset is utf-8), it goes like this on the database:
=?utf-8?Q?=D7=A8=D7=A9=D7=99=D7=9E=D7=AA_=D7=94=D7=A6?=
 =?utf-8?Q?=D7=99=D7=95=D7=93_=D7=9C=D7=9E=D7=A9=D7=97=D7=A7_=D7=A0=D7=92?=
 =?utf-8?Q?=D7=93_=D7=A8=D7=99=D7=90=D7=9C_=D7=9E=D7=93=D7=A8=D7=99=D7=93?=
 =?utf-8?Q?_=D7=A4=D7=95=D7=A8=D7=A1=D7=9E=D7=94!?=

**Comment by neochief** [comment]
Are you sure that this is not DB's collation issue?

**Comment by neochief** [comment]
Okay, the issue should be fixed now, I've found the problem.
