### ISSUE TITLE
Sending Mail With Attachment Returns DB error

### ISSUE THREAD

**Issue by DevinNorgarb** [shvetsgroup/laravel-email-database-log#8]
Useful Package guys,

I have used it on a few projects but having trouble with sending mails with attachments, like PDF documents since it seems to try insert the PDF into the DB.

Sample error: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\x9C\x03\x00\x00\x00\x00...' for column 'body' at row 1.

I have tried ->attachData() and ->attach() with no luck.
PHP7.0 and Laravel 5.4

**Comment by uuur86** [comment]
Seems like data type error 

> "Incorrect string value"

 but  

> '\x9C\x03\x00\x00\x00\x00...'

 **not a string value**. 

May you are wrongly use this function. Such as;
It may needed a path as a string, but you load file hex data 

You must first change hex data to string. I dont know attachData or attach functions because i have never used to laravel.

**Comment by divdax** [comment]
When your message contains an attachment (which is inside the mail body) you should use BLOB as datatype for your body column.

**Comment by neochief** [comment]
So it looks that this issue can be closed now?

**Comment by neochief** [comment]
Actually, I've investigated and fixed this problem. Attachments are now bas64 encoded and placed into a separate database field.

**Comment by divdax** [comment]
The attachment column is only from type `TEXT`.

> TEXT: 65,535 characters - 64 KB

This means attachments greater than ~64KB will be stored corrupted.
Instead the column should be `LONGBLOB`.

> Type: LONGBLOB
> A binary large object column with a maximum length of 4294967295 (2^32 - 1) characters

I doesn't have the time to do a PR but even more efficient would be a simple VARCHAR, disk & path column and storing files on the disks. Your database is small even after sending 100GB attachments, and you can choose where your files are stored. local, s3...
