### ISSUE TITLE
Instance of Swift_Mime_MimeEntity expected, received Swift_Message instance

### ISSUE THREAD

**Issue by markdieselcore** [shvetsgroup/laravel-email-database-log#9]
I'm trying to use this package to log emails in Laravel 5.5. I'm queuing my email class like so:

    $jobId = Mail::to('myemail@domain.com')->queue(new ApiEmail($data));

However, I'm getting an error:

    Argument 1 passed to ShvetsGroup\LaravelEmailDatabaseLog\EmailLogger::getMimeEntityString() must be an instance of Swift_Mime_MimeEntity, instance of Swift_Message given, called in ShvetsGroup/LaravelEmailDatabaseLog/EmailLogger.php on line 23 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to ShvetsGroup\\LaravelEmailDatabaseLog\\EmailLogger::getMimeEntityString() must be an instance of Swift_Mime_MimeEntity, instance of Swift_Message given, called in /vendor/shvetsgroup/laravel-email-database-log/src/ShvetsGroup/LaravelEmailDatabaseLog/EmailLogger.php on line 23 at /vendor/shvetsgroup/laravel-email-database-log/src/ShvetsGroup/LaravelEmailDatabaseLog/EmailLogger.php:33)

Any idea why this is happening?

**Comment by divdax** [comment]
The EmailLogger should be updated.

Use```Swift_Mime_SimpleMimeEntity``` instead of ```Swift_Mime_SimpleMimeEntity```.
```php
protected function getMimeEntityString(\Swift_Mime_SimpleMimeEntity $entity)
{
    $string = (string) $entity->getHeaders().PHP_EOL.$entity->getBody();
    foreach ($entity->getChildren() as $children) {
        $string .= PHP_EOL.PHP_EOL.$this->getMimeEntityString($children);
    }
    return $string;
}
```

**Comment by neochief** [comment]
I removed the type hinting in the recent release, so this shouldn't be a problem anymore.
